### ISSUE TITLE
Upgrading flux2

### ISSUE THREAD

**Issue by onedr0p** [timtorChen/pi-cluster#93]
### Describe the bug 

Currently you have renovate upgrading Flux individual docker images, this way is not the proper way to upgrade Flux according to [their docs](https://toolkit.fluxcd.io/guides/installation/#upgrade). This is because their manifests include more than just image upgrades on version changes.

For me I found it useful to create a [Github workflow](https://github.com/onedr0p/home-cluster/blob/main/.github/workflows/flux-schedule.yaml) to upgrade flux.

**Comment by timtorChen** [comment]
Oh, I did not notice this problem. 
Thank you for this issue opening and your solution, I really learn a lot from your repo!
